title: Pargame
email: 001201parg@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

# twitter_username: jekyllrb
github_username: pargame

# Build settings
theme: minima
minima:
  skin: dark

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-lazy-load-image

header_pages:
  - about.md
  - studies.md
  - projects.md
  - categories.md
  - tags.md
  - search.md

collections:
  studies:
    output: true
    permalink: /studies/:path/
  projects:
    output: true
    permalink: /projects/:path/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# files' path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Defaults for specific paths
defaults:
  -
    scope:
      path: ""
      type: "studies"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
\n# Site Version\nversion: 1.2.0
