title: MyProfile
email: 001201parg@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

# twitter_username: jekyllrb
github_username: pargame

# Comment system
disqus:
  shortname: # 여기에 Disqus shortname을 입력하세요. 예: myprofile-blog

# Build settings
theme: minima
minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - about.md
  - studies.md
  - projects.md
  - categories.md
  - tags.md

collections:
  studies:
    output: true
  projects:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# files' path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
