title: Pargame
email: 001201parg@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

# twitter_username: jekyllrb
github_username: pargame

# Comment system (Disqus)
# To enable comments, create an account at https://disqus.com/ and enter your "shortname" here.
# For example: shortname: my-awesome-blog
disqus:
  shortname: your-disqus-shortname-goes-here # <--- 중요: 실제 댓글 기능을 사용하려면 이 값을 당신의 Disqus shortname으로 바꾸세요.

# Build settings
theme: minima
minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-lazy-load-image
  - simple-jekyll-search

header_pages:
  - about.md
  - studies.md
  - projects.md
  - categories.md
  - tags.md
  - search.md

collections:
  studies:
    output: true
  projects:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# files' path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
