title: MyProfile
description: "A simple Jekyll site for my profile."

header_pages:
  - about.md
  - projects.md
  - studies.md

style: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
exclude:
  - .gemini/
  - .gitignore
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/